server:
  port: 4556
  servlet:
    context-path: /peepol-api

spring:
  threads:
    virtual:
      enabled: true

  application:
    name: peepol

  datasource:
    url: ${SPRING_DATASOURCE_URL:no-conn}
    username: ${SPRING_DATASOURCE_USERNAME:no-username}
    password: ${SPRING_DATASOURCE_PASSWORD:no-pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  paseto:
    secret_key: ${PASETO_SECRET_KEY:no-key}
